development:
  cloud_name: AppConfig.CLOUDINARY_NAME
  api_key: AppConfig.CLOUDINARY_KEY
  api_secret: AppConfig.CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: AppConfig.CLOUDINARY_NAME
  api_key: AppConfig.CLOUDINARY_KEY
  api_secret: AppConfig.CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: AppConfig.CLOUDINARY_NAME
  api_key: AppConfig.CLOUDINARY_KEY
  api_secret: AppConfig.CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: false
